# Generated by Django 4.0.3 on 2022-03-28 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='영화제목')),
                ('year', models.PositiveIntegerField(default=0, verbose_name='제작년도')),
                ('original_title', models.CharField(max_length=100, null=True, verbose_name='원제')),
                ('video_url1', models.URLField(null=True, verbose_name='영상주소')),
                ('video_url2', models.URLField(null=True, verbose_name='영상주소')),
                ('video_url3', models.URLField(null=True, verbose_name='영상주소')),
                ('video_url4', models.URLField(null=True, verbose_name='영상주소')),
                ('cast', models.CharField(max_length=100, verbose_name='출연진')),
                ('synopsis', models.TextField(verbose_name='시놉시스')),
                ('image', models.ImageField(default='media/', upload_to='', verbose_name='포스터')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='MovieOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('grade', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='평점')),
                ('runningtime', models.CharField(max_length=100, verbose_name='재생시간')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_option', to='movies.movie')),
            ],
            options={
                'db_table': 'MovieOption',
            },
        ),
        migrations.CreateModel(
            name='AttentionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watchlist', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('is_like', models.BooleanField(default=False)),
                ('is_dislike', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_Attention_list', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AttentionList',
            },
        ),
    ]
