# Generated by Django 4.0.3 on 2022-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentionlist',
            name='is_dislike',
            field=models.BooleanField(verbose_name='Dislike'),
        ),
        migrations.AlterField(
            model_name='attentionlist',
            name='is_like',
            field=models.BooleanField(verbose_name='좋아요'),
        ),
        migrations.AlterField(
            model_name='attentionlist',
            name='is_seen',
            field=models.BooleanField(verbose_name='Seen'),
        ),
        migrations.AlterField(
            model_name='attentionlist',
            name='is_watchlist',
            field=models.BooleanField(verbose_name='시청목록'),
        ),
    ]
